#!/usr/bin/env bash
#Bash script that displays Best School 10x

S=("Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School" "Best School")

for i in "${S[@]}";
do
	echo "$i"
done
