#!/usr/bin/env bash
#Bash Script that displays Best School 10x

school=1
while [ "$school" -le 20 ]
do
	case $school in

		4)
		echo -e "4\nbad luck from China";;
		9)
		echo -e "9\nbad luck from Japan";;
		17)
		echo -e "17\nbad luck from Italy";;
		*)
			echo "$school"
	esac
	school=$(( school+1 ))
done
