#!/usr/bin/env bash
#Displays an archaic clock

hours=0
while [[ $hours -le 12 ]]
do
	echo "Hour: $hours"
	min=1	
	while [[ $min -le 59 ]]
	do
		echo "$min"
		min=$((min+1))	
	done
	hours=$((hours+1))
done
